//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebMedico.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourcesAccount {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourcesAccount() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebMedico.Properties.ResourcesAccount", typeof(ResourcesAccount).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morada.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta!.
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desculpe por algum inconveniente na autenticação.
        /// </summary>
        public static string AuthenticationIssues {
            get {
                return ResourceManager.GetString("AuthenticationIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Palavra-passe (deve corresponder ao valor inserido no campo Palavra-passe).
        /// </summary>
        public static string ComparePassword {
            get {
                return ResourceManager.GetString("ComparePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certifique-se de completar os seguintes campos:.
        /// </summary>
        public static string CompleteFields {
            get {
                return ResourceManager.GetString("CompleteFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação de Login.
        /// </summary>
        public static string ConfirmLogin {
            get {
                return ResourceManager.GetString("ConfirmLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Palavra-passe.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmação de registro.
        /// </summary>
        public static string ConfirmRegister {
            get {
                return ResourceManager.GetString("ConfirmRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cortar.
        /// </summary>
        public static string crop {
            get {
                return ResourceManager.GetString("crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo inválido. Precisa ser pelo menos 100x100 pixels..
        /// </summary>
        public static string croperror {
            get {
                return ResourceManager.GetString("croperror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clique e arraste para mover. Mantenha a tecla shift na escala..
        /// </summary>
        public static string cropinstructions {
            get {
                return ResourceManager.GetString("cropinstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cortar imagem.
        /// </summary>
        public static string croptitle {
            get {
                return ResourceManager.GetString("croptitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de criação.
        /// </summary>
        public static string DateCreated {
            get {
                return ResourceManager.GetString("DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de nascimento.
        /// </summary>
        public static string DateofBirth {
            get {
                return ResourceManager.GetString("DateofBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail já existe.
        /// </summary>
        public static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo de E-mail não é válido.
        /// </summary>
        public static string EmailBadFormat {
            get {
                return ResourceManager.GetString("EmailBadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feminino.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esqueci Palavra-passe.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Género.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de inicio da carreira.
        /// </summary>
        public static string InitDateCareer {
            get {
                return ResourceManager.GetString("InitDateCareer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idiomas.
        /// </summary>
        public static string Languages {
            get {
                return ResourceManager.GetString("Languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apelido.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A carregar....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localidade.
        /// </summary>
        public static string Locality {
            get {
                return ResourceManager.GetString("Locality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masculino.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to medicos.cc.
        /// </summary>
        public static string medicoscc {
            get {
                return ResourceManager.GetString("medicoscc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O {0} deve ter pelo menos {2} caracteres por muito tempo..
        /// </summary>
        public static string MinimunLength {
            get {
                return ResourceManager.GetString("MinimunLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número de telemovel.
        /// </summary>
        public static string Mobile_Number {
            get {
                return ResourceManager.GetString("Mobile_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número da ordem.
        /// </summary>
        public static string OrderNumber {
            get {
                return ResourceManager.GetString("OrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palavra-passe.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto de perfil.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Memorizar credenciais.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo de Morada é obrigatório.
        /// </summary>
        public static string RequiredAddress {
            get {
                return ResourceManager.GetString("RequiredAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo de Email é obrigatório.
        /// </summary>
        public static string RequiredEmail {
            get {
                return ResourceManager.GetString("RequiredEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo de Género é obrigatório.
        /// </summary>
        public static string RequiredGender {
            get {
                return ResourceManager.GetString("RequiredGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo de Data de inicio da carreira é obrigatório.
        /// </summary>
        public static string RequiredInitDateCareer {
            get {
                return ResourceManager.GetString("RequiredInitDateCareer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo de Apelido é obrigatório.
        /// </summary>
        public static string RequiredLastName {
            get {
                return ResourceManager.GetString("RequiredLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo de Localidade é obrigatório.
        /// </summary>
        public static string RequiredLocality {
            get {
                return ResourceManager.GetString("RequiredLocality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo de Número de telemovel é obrigatório.
        /// </summary>
        public static string RequiredMobile_Number {
            get {
                return ResourceManager.GetString("RequiredMobile_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo de Nome é obrigatório.
        /// </summary>
        public static string RequiredName {
            get {
                return ResourceManager.GetString("RequiredName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo de Número da ordem é obrigatório.
        /// </summary>
        public static string RequiredOrderNumber {
            get {
                return ResourceManager.GetString("RequiredOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo da Palavra-passe é obrigatório.
        /// </summary>
        public static string RequiredPassword {
            get {
                return ResourceManager.GetString("RequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo de Specialty é obrigatório.
        /// </summary>
        public static string RequiredSpecialty {
            get {
                return ResourceManager.GetString("RequiredSpecialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo de Contribuinte é obrigatório.
        /// </summary>
        public static string RequiredTaxPayer {
            get {
                return ResourceManager.GetString("RequiredTaxPayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo de Codigo postal é obrigatório.
        /// </summary>
        public static string RequiredZipCode {
            get {
                return ResourceManager.GetString("RequiredZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservado a profissionais.
        /// </summary>
        public static string ReservedforProfessionals {
            get {
                return ResourceManager.GetString("ReservedforProfessionals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Especialidade.
        /// </summary>
        public static string Specialty {
            get {
                return ResourceManager.GetString("Specialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passo 1.
        /// </summary>
        public static string Step1 {
            get {
                return ResourceManager.GetString("Step1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passo 2.
        /// </summary>
        public static string Step2 {
            get {
                return ResourceManager.GetString("Step2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passo 3.
        /// </summary>
        public static string Step3 {
            get {
                return ResourceManager.GetString("Step3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribuinte.
        /// </summary>
        public static string TaxPayer {
            get {
                return ResourceManager.GetString("TaxPayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENTENDI.
        /// </summary>
        public static string Understood {
            get {
                return ResourceManager.GetString("Understood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário encontrado.
        /// </summary>
        public static string UserFound {
            get {
                return ResourceManager.GetString("UserFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário não encontrado.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codigo postal.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
    }
}
